import string,nltk,re

def read_file(filename):
    r"""Assume the file is the format
    word \t tag
    word \t tag
    [[blank line separates sentences]]
    
    This function reads the file and returns a list of sentences.  each
    sentence is a pair (tokens, tags), each of which is a list of strings of
    the same length.
    """
    sentences = open(filename).read().strip().split("\n\n")
    ret = []
    for sent in sentences:
        lines = sent.split("\n")
        pairs = [L.split("\t") for L in lines]
        tokens = [tok for tok,tag in pairs]
        tags = [tag for tok,tag in pairs]
        ret.append( (tokens,tags) )
    return ret

def clean_str(s):
    """Clean a word string so it doesn't contain special crfsuite characters"""
    return s.replace(":","_COLON_").replace("\\", "_BACKSLASH_")

def extract_features_for_sentence1(tokens):
    N = len(tokens)
    feats_per_position = [set() for i in range(N)]
    for t in range(N):
        w = clean_str(tokens[t])
        feats_per_position[t].add("word=%s" % w)
    return feats_per_position

def extract_features_for_sentence2(tokens):
    N = len(tokens)
    feats_per_position = [set() for i in range(N)]
    PoS=nltk.pos_tag(tokens)
    for t in range(N):
        w = clean_str(tokens[t])
        tag="O"
        if "NNP" in PoS[t] or "NNPS" in PoS[t]:
            tag="B"
        if tag=="B":
            if containsSymbol(w):
                tag="O"
            if isMonth(w):
                tag="O"
        if tag=="O":
            if isCountry(w):
                tag="B"
        feats_per_position[t].add("%s\tword=%s" %(tag,w))
    return feats_per_position
def isCountry(word):
    countries={
        "AD",
        "ANDORRA",
        "AE",
        "UNITED ARAB EMIRATES",
        "AF",
        "AFGHANISTAN",
        "AG",
        "ANTIGUA AND BARBUDA",
        "AI",
        "ANGUILLA",
        "AL",
        "ALBANIA",
        "AM",
        "ARMENIA",
        "AN",
        "NETHERLANDS ANTILLES",
        "AO",
        "ANGOLA",
        "AQ",
        "ANTARCTICA",
        "AR",
        "ARGENTINA",
        "AS",
        "AMERICAN SAMOA",
        "AT",
        "AUSTRIA",
        "AU",
        "AUSTRALIA"
        "AW",
        "ARUBA",
        "AZ",
        "AZERBAIJAN",
        "BA",
        "BOSNIA AND HERZEGOVINA",
        "BB",
        "BARBADOS",
        "BD",
        "BANGLADESH",
        "BE",
        "BELGIUM",
        "BF",
        "BURKINA FASO"
        "BG",
        "BULGARIA",
        "BH",
        "BAHRAIN",
        "BI",
        "BURUNDI",
        "BJ",
        "BENIN",
        "BM",
        "BERMUDA",
        "BN",
        "BRUNEI DARUSSALAM",
        "BO",
        "BOLIVIA",
        "BR",
        "BRAZIL",
        "BS",
        "BAHAMAS",
        "BT",
        "BHUTAN",
        "BV",
        "BOUVET ISLAND",
        "BW",
        "BOTSWANA",
        "BY",
        "BELARUS",
        "BZ",
        "BELIZE",
        "CA",
        "CANADA",
        "CC",
        "COCOS (KEELING) ISLANDS",
        "CD",
        "CONGO, THE DEMOCRATIC REPUBLIC OF THE",
        "CF",
        "CENTRAL AFRICAN REPUBLIC",
        "CG",
        "CONGO"
        "CH",
        "SWITZERLAND"
        "CI",
        "C�TE D'IVOIRE"
        "CK",
        "COOK ISLANDS",
        "CL",
        "CHILE",
        "CM",
        "CAMEROON",
        "CN",
        "CHINA",
        "CO",
        "COLOMBIA",
        "CR",
        "COSTA RICA"
        "CU",
        "CUBA",
        "CV",
        "CAPE VERDE",
        "CX",
        "CHRISTMAS ISLAND",
        "CY",
        "CYPRUS",
        "CZ",
        "CZECH REPUBLIC",
        "DE",
        "GERMANY",
        "DJ",
        "DJIBOUTI",
        "DK",
        "DENMARK",
        "DM",
        "DOMINICA",
        "DO",
        "DOMINICAN REPUBLIC",
        "DZ",
        "ALGERIA",
        "EC",
        "ECUADOR",
        "EE",
        "ESTONIA",
        "EG",
        "EGYPT",
        "EH",
        "WESTERN SARARA",
        "ER",
        "ERITREA",
        "ES",
        "SPAIN",
        "ET",
        "ETHIOPIA",
        "FI",
        "FINLAND",
        "FJ",
        "FIJI",
        "FK",
        "FALKLAND ISLANDS (MALVINAS)",
        "FM",
        "MICRONESIA, FEDERATED STATES OF",
        "FO",
        "FAROE ISLANDS",
        "FR",
        "FRANCE",
        "GA",
        "GABON",
        "GB",
        "UNITED KINGDOM",
        "GD",
        "GRENADA",
        "GE",
        "GEORGIA",
        "GF",
        "FRENCH GUIANA",
        "GH",
        "GHANA",
        "GI",
        "GIBRALTAR",
        "GL",
        "GREENLAND",
        "GM",
        "GAMBIA",
        "GN",
        "GUINEA",
        "GP",
        "GUADELOUPE",
        "GQ",
        "EQUATORIAL GUINEA",
        "GR",
        "GREECE",
        "GS",
        "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
        "GT",
        "GUATEMALA",
        "GU",
        "GUAM",
        "GW",
        "GUINEA-BISSAU",
        "GY",
        "GUYANA",
        "HK",
        "HONG KONG",
        "HM",
        "HEARD ISLAND AND MCDONALD ISLANDS",
        "HN",
        "HONDURAS",
        "HR",
        "CROATIA",
        "HT",
        "HAITI",
        "HU",
        "HUNGARY",
        "ID",
        "INDONESIA",
        "IE",
        "IRELAND",
        "IL",
        "ISRAEL",
        "IN",
        "INDIA",
        "IO",
        "BRITISH INDIAN OCEAN TERRITORY",
        "IQ",
        "IRAQ",
        "IR",
        "IRAN, ISLAMIC REPUBLIC OF",
        "IS",
        "ICELAND",
        "IT",
        "ITALY",
        "JM",
        "JAMAICA",
        "JO",
        "JORDAN",
        "JP",
        "JAPAN",
        "KE",
        "KENYA",
        "KG",
        "KYRGYZSTAN",
        "KH",
        "CAMBODIA",
        "KI",
        "KIRIBATI",
        "KM",
        "COMOROS",
        "KN",
        "SAINT KITTS AND NEVIS",
        "KP",
        "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
        "KR",
        "KOREA, REPUBLIC OF",
        "KW",
        "KUWAIT",
        "KY",
        "CAYMAN ISLANDS",
        "KZ",
        "KAZAKHSTAN",
        "LA",
        "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
        "LB",
        "LEBANON",
        "LC",
        "SAINT LUCIA",
        "LI",
        "LIECHTENSTEIN",
        "LK",
        "SRI LANKA",
        "LR",
        "LIBERIA",
        "LS",
        "LESOTHO",
        "LT",
        "LITHUANIA",
        "LU",
        "LUXEMBOURG",
        "LV",
        "LATVIA",
        "LY",
        "LIBYAN ARAB JAMABIRIYA",
        "MA",
        "MOROCCO",
        "MC",
        "MONACO",
        "MD",
        "MOLDOVA, REPUBLIC OF",
        "MG",
        "MADAGASCAR",
        "MH",
        "MARSHALL ISLANDS",
        "MK",
        "MACEDONIA, THE FORMER YUGOSLAV REPU8LIC OF",
        "ML",
        "MALI",
        "MM",
        "MYANMAR",
        "MN",
        "MONGOLIA",
        "MO",
        "MACAU",
        "MP",
        "NORTHERN MARIANA ISLANDS",
        "MQ",
        "MARTINIQUE",
        "MR",
        "MAURITANIA",
        "MS",
        "MONTSERRAT",
        "MT",
        "MALTA",
        "MU",
        "MAURITIUS",
        "MV",
        "MALDIVES",
        "MW",
        "MALAWI",
        "MX",
        "MEXICO",
        "MY",
        "MALAYSIA",
        "MZ",
        "MOZAMBIQUE",
        "NA",
        "NAMIBIA",
        "NC",
        "NEW CALEDONIA",
        "NE",
        "NIGER",
        "NF",
        "NORFOLK ISLAND",
        "NG",
        "NIGERIA",
        "NI",
        "NICARAGUA",
        "NL",
        "NETHERLANDS",
        "NO",
        "NORWAY",
        "NP",
        "NEPAL",
        "NU",
        "NIUE",
        "NZ",
        "NEW ZEALAND",
        "OM",
        "OMAN",
        "PA",
        "PANAMA",
        "PE",
        "PERU",
        "PF",
        "FRENCH POLYNESIA",
        "PG",
        "PAPUA NEW GUINEA",
        "PH",
        "PHILIPPINES",
        "PK",
        "PAKISTAN",
        "PL",
        "POLAND",
        "PM",
        "SAINT PIERRE AND MIQUELON",
        "PN",
        "PITCAIRN",
        "PR",
        "PUERTO RICO",
        "PT",
        "PORTUGAL",
        "PW",
        "PALAU",
        "PY",
        "PARAGUAY",
        "QA",
        "QATAR",
        "RE",
        "R�UNION",
        "RO",
        "ROMANIA",
        "RU",
        "RUSSIAN FEDERATION",
        "RW",
        "RWANDA",
        "SA",
        "SAUDI ARABIA",
        "SB",
        "SOLOMON ISLANDS",
        "SC",
        "SEYCHELLES",
        "SD",
        "SUDAN",
        "SE",
        "SWEDEN",
        "SG",
        "SINGAPORE",
        "SH",
        "SAINT HELENA",
        "SI",
        "SLOVENIA",
        "SJ",
        "SVALBARD AND JAN MAYEN",
        "SK",
        "SLOVAKIA",
        "SL",
        "SIERRA LEONE",
        "SM",
        "SAN MARINO",
        "SN",
        "SENEGAL",
        "SO",
        "SOMALIA",
        "SR",
        "SURINAME",
        "ST",
        "SAO TOME AND PRINCIPE",
        "SV",
        "EL SALVADOR",
        "SY",
        "SYRIAN ARAB REPUBLIC",
        "SZ",
        "SWAZILAND",
        "TC",
        "TURKS AND CAICOS ISLANDS",
        "TD",
        "CHAD",
        "TF",
        "FRENCH SOUTHERN TERRITORIES",
        "TG",
        "TOGO",
        "TH",
        "THAILAND",
        "TJ",
        "TAJIKISTAN",
        "TK",
        "TOKELAU",
        "TM",
        "TURKMENISTAN",
        "TN",
        "TUNISIA",
        "TO",
        "TONGA",
        "TP",
        "EAST TIMOR",
        "TR",
        "TURKEY",
        "TT",
        "TRINIDAD AND TOBAGO",
        "TV",
        "TUVALU",
        "TW",
        "TAIWAN, PROVINCE OF CHINA",
        "TZ",
        "TANZANIA, UNITED REPUBLIC OF",
        "UA",
        "UKRAINE",
        "UG",
        "UGANDA",
        "UM",
        "UNITED STATES MINOR OUTLYING ISLANDS",
        "US",
        "UNITED STATES",
        "UY",
        "URUGUAY",
        "UZ",
        "UZBEKISTAN",
        "VE",
        "VENEZUELA",
        "VG",
        "VIRGIN ISLANDS, BRITISH",
        "VI",
        "VIRGIN ISLANDS, U.S.",
        "VN",
        "VIET NAM",
        "VU",
        "VANUATU",
        "WF",
        "WALLIS AND FUTUNA",
        "WS",
        "SAMOA",
        "YE",
        "YEMEN",
        "YT",
        "MAYOTTE",
        "YU",
        "YUGOSLAVIA",
        "ZA",
        "SOUTH AFRICA",
        "ZM",
        "ZAMBIA",
        "ZW",
        "ZIMBABWE",
    }
    if word in countries:
        return True
    return False
def containsSymbol(word):
    return re.match("^[\w]+$",word) is None
def isMonth(word):
    months={
        #"jan":True,
        "january":True,
        "feb":True,
        "february":True,
        "mar":True,
        "march":True,
        "apr":True,
        #"april":True,
        "jun":True,
        #"june":True,
        "jul":True,
        "july":True,
        "aug":True,
        "august":True,
        "sep":True,
        "september":True,
        "oct":True,
        "october":True,
        "nov":True,
        "november":True,
        "dec":True,
        "december":True
    }
    if word.lower() in months:
        return True
    return False

extract_features_for_sentence = extract_features_for_sentence2

def extract_features_for_file(input_file, output_file):
    """This runs the feature extractor on input_file, and saves the output to
    output_file."""
    sents = read_file(input_file)
    with open(output_file,'w') as output_fileobj:
        for tokens,goldtags in sents:
            feats = extract_features_for_sentence(tokens)
            for t in range(len(tokens)):
                feats_tabsep = "\t".join(feats[t])
                print>>output_fileobj, "%s" % (feats_tabsep)
            print>>output_fileobj, ""

extract_features_for_file("train.txt", "train.feats")
extract_features_for_file("dev.txt", "dev.feats")
